### ISSUE TITLE
Incorrect PATH in install.xml

### ISSUE THREAD

**Issue by azito122** [Swarthmore/block-filescan#24]
The path is set to `block/filescan/db`, but should be `blocks/filescan/db`. This causes installing on at east 3.5.1 to explode. Here is a [related MDL-Tracker issue](https://tracker.moodle.org/browse/MDL-61150).

Error:
```
Errors found in XMLDB file: PATH attribute does not match file directory: blocks/filescan/db
Error code: ddlxmlfileerror
```

**Comment by aruethe2** [comment]
Thanks for letting me know and linking to the Moodle Tracker issue.  Please comment back if you have any additional problems.
