### ISSUE TITLE
Set up events to invalidate cache

### ISSUE THREAD

**Issue by aruethe2** [Swarthmore/block-filescan#25]
The file scan summary information in the block is cached so doesn't need to recalculate on every page load.  Currently, only clicking on "View File Details" will force a cache refresh.  

Ideally the cache would be invalidated each time a PDF file was uploaded to the course, but perhaps it could be invalidated on a time cycle or other event.  According to the [Moodle Dev documentation](https://docs.moodle.org/dev/Cache_API#Cache_modifiers), setting a time to live (ttl) is not recommended.

**Comment by mackensen** [comment]
I'd vote for invalidation when a PDF is uploaded to a course, that would match a user's expectations but (probably) wouldn't create a massive amount of overhead.

**Comment by aruethe2** [comment]
Resolved by PR #30
