### ISSUE TITLE
Site administration navigation breaks in Moodle 3.2 with Clean

### ISSUE THREAD

**Issue by kwiliarty** [Swarthmore/block-filescan#8]
Maybe this is related to #5? At any rate, I'm using Moodle 3.2 with a Clean-based theme. When I install the plugin the 'Site administration' menu in the administration block stops working. When I remove the plugin, that menu starts working again. Because it is large the menu loads only when called for. I can see the loading spinner, but then it comes back empty. If I go to `/admin` manually everything works fine.

**Comment by aruethe2** [comment]
I developed the block using the Clean theme and didn't notice any problem on my install, but I have done limited testing on other browsers/OS's.  

I'l check it out and see if we can figure out what is going on.

**Comment by kwiliarty** [comment]
Ah, so here's something to try. Set Moodle's debugging to the highest level, and then see what happens. For my part, if I turn debugging off, that solves the problem. Debugging does not usually have the effect of breaking the navigation, but if there is a warning in the AJAX request for the menu then I guess it could cause it to fail. The upshot is that this is probably just a symptom, maybe of #5 after all. Could also be the missing strings. At any rate, when there are no warnings it will probably fix itself.

**Comment by mackensen** [comment]
See pull request #12. It's especially obvious if you're trying to download a file; you get the dreaded "output has already started" error.
